version: "3"
services:
  postgres:
    build: .
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - config/.env

volumes:
  postgres_volume: